# Generated by Django 3.2.2 on 2021-05-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverfname', models.CharField(max_length=30)),
                ('driverlname', models.CharField(max_length=30)),
                ('drivertel', models.IntegerField(max_length=10)),
                ('attendantfname', models.CharField(max_length=30)),
                ('attendantlname', models.CharField(max_length=30)),
                ('attendanttel', models.IntegerField(max_length=10)),
                ('brand', models.CharField(max_length=30)),
                ('vancode', models.CharField(max_length=30)),
                ('schoolcode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=50)),
                ('schoolcode', models.CharField(max_length=50)),
                ('schooladdress', models.CharField(max_length=100)),
                ('schoolmail', models.EmailField(max_length=30)),
                ('schooltel', models.IntegerField(max_length=10)),
                ('schoolfax', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Std_parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdfname', models.CharField(max_length=30)),
                ('stdlname', models.CharField(max_length=30)),
                ('stdaddress', models.CharField(max_length=100)),
                ('stdemail', models.EmailField(max_length=30)),
                ('stdcounty', models.CharField(max_length=30)),
                ('stdpostalcode', models.IntegerField(max_length=5)),
                ('stdmacaddress', models.CharField(max_length=30)),
                ('fatherfname', models.CharField(max_length=30)),
                ('fatherlname', models.CharField(max_length=30)),
                ('motherfname', models.CharField(max_length=30)),
                ('motherlname', models.CharField(max_length=30)),
                ('parenttel', models.IntegerField(max_length=10)),
                ('parenttelback', models.IntegerField(max_length=10)),
            ],
        ),
    ]
